---
title: 18 - 调试、测试
tags: assert,pdb,set_trace,单元测试,文档测试,unittest
renderNumberedHeading: true
grammar_cjkRuby: true
---

Author:  Qiao My
Create_Time: 2020-3-15

[toc]
# 一、调试
程序写完一次正常运行的概率很小，总有各种bug，因此，需要一整套调试程序的手段修复bug。

可以通过print() 打印出可能有问题的变量，但print() 打印的方法，缺点在于调试完成后需要删掉。

## 1. 断言(assert)
assert 语句是在程序中插入调试性断言的简便方式。凡是用`print()`来辅助查看的地方，都可以断言(assert)来替代。

语法：
```python
assert expression0 [, expression1]
```
当expression0不满足时，则抛出 `AssertionError`，如果expression1被指定，则抛出`AssertionError(expression1)`
等价于
```python
# 简单形式，传入一个参数
if __debug__:
    if not expression: raise AssertionError
# 扩展形式，传入一个参数
if __debug__:
    if not expression1: raise AssertionError(expression2)
```

启动Python解释器时，可以用`-O`参数关闭`assert`。注意这里的`-O`是大写英文字母。
关闭后，可以把`assert`当做`pass`看。

## 2. logging
见 17 - 错误处理try - 记录错误(logging 模块)

## 3. pdb
以参数`-m pdb` 启动调试。
语法：
```bash
python3 -m pdb myscript.py
```
pdb命令；
`1`: 查看代码
`n`: next，单步执行代码。
`p 变量名`: 查看变量
`q`: 结束调试，退出程序
`c`: 继续。也可以是`cont`、`continue`

## 4. pdb.set_trace()
本方法也是用 pdb，但不需要单步执行。`import pdb`之后，只需在可能出错的地方放一个`pdb.set_trace()`，就可以设置一个断点。
程序会在`pdb.set_trace()`暂停并进入 pdb 调试环境。

例：
```python
import pdb

s = '0'
n = int(s)
pdb.set_trace() # 运行到这里会自动暂停
print(10 / n)

# 运行
$ python err.py 
> /Users/michael/Github/learn-python3/samples/debug/err.py(7)<module>()
-> print(10 / n)
(Pdb) p n
0
(Pdb) c
Traceback (most recent call last):
  File "err.py", line 7, in <module>
    print(10 / n)
ZeroDivisionError: division by zero
```


# 二、测试
## 1. 单元测试
单元测试是用来对一个模块、一个函数或者一个类进行正确性检验的测试工作。
如果单元测试通过，说明测试的函数能够正常工作；如果单元测试不通过，则说明函数有bug或测试条件输入有误，需要修复。

单元测试通过的意义在于，对已经通过单元测试的函数再次进行修改后，可以通过再次的单元测试验证是否与函数修改前原有行为一致。

这种以测试为驱动的开发模式，最大的好处就是确保一个程序模块行为符合我们设计的测试用例。在将来修改的时候，可以极大程度的保证该模块行为仍然是正确的。

编写测试单元时，需要编写测试类，该类从`unittest.TestCase`继承
以`test`开头的方法就是测试方法，不以`test`开头的方法不被认为是测试方法，测试时不会被执行。
对每一类测试都要表写一个`test_xxx()`方法。由于`unittest.TestCase`提供了很多内置的条件判断，只需要调用这些方法就可以断言输出是否是我们所期望的。
最常用的断言就是`assertEqual()`断言两个值相等、`assertRaises`断言抛出期待类型的Error。
例：
单元代码
```python
# mydict2.py
class Dict(dict):

    def __init__(self, **kw):
        super().__init__(**kw)

    def __getattr__(self, key):
        try:
            return self[key]
        except KeyError:
            raise AttributeError(r"'Dict' object has no attribute '%s'" % key)

    def __setattr__(self, key, value):
        self[key] = value
```

测试代码
```python
# mydict_test.py
import unittest

from mydict import Dict

class TestDict(unittest.TestCase):

    def test_init(self):
        d = Dict(a=1, b='test')
        self.assertEqual(d.a, 1)
        self.assertEqual(d.b, 'test')
        self.assertTrue(isinstance(d, dict))

    def test_key(self):
        d = Dict()
        d['key'] = 'value'
        self.assertEqual(d.key, 'value')

    def test_attr(self):
        d = Dict()
        d.key = 'value'
        self.assertTrue('key' in d)
        self.assertEqual(d['key'], 'value')

    def test_keyerror(self):
        d = Dict()
        with self.assertRaises(KeyError):
            value = d['empty']

    def test_attrerror(self):
        d = Dict()
        with self.assertRaises(AttributeError):
            value = d.empty
```

### 运行单元测试
方法1：推荐方法**，通过参数`-m unittest`直接运行单元测试。可以一次批量运行多个单元测试**
```bash
$ python -m unittest mydict_test
.....
----------------------------------------------------------------------
Ran 5 tests in 0.000s

OK
```
方法2: 模块内调用
```python
if __name__ == '__main__':
    unittest.main()
```
方法3: 脚本式
```bash
$ python mydict_test.py
```

### setUp与tearDown
假如测试需要启动一个数据库，此时可以在`setUp()`方法中连接数据库，在`tearDown()`方法中关闭数据库。
避免在每个测试方法中重复相同的代买
例：
```python
class TestDict(unittest.TestCase):

    def setUp(self):
        print('setUp...')

    def tearDown(self):
        print('tearDown...')
```

## 2. 文档测试
Python内置的“文档测试”(`doctest`)模块可以直接提取注释中的代码并执行测试。
`doctest`严格按照Python交互式命令行的输入和输出来判断测试结构是否正确。
只有测试异常的时候，可以用`...`表示中间一大堆的输出。
例：
使用`doctest`改写`Dict`类
```python
# mydict2.py
class Dict(dict):
    '''
    Simple dict but also support access as x.y style.

    >>> d1 = Dict()
    >>> d1['x'] = 100
    >>> d1.x
    100
    >>> d1.y = 200
    >>> d1['y']
    200
    >>> d2 = Dict(a=1, b=2, c='3')
    >>> d2.c
    '3'
    >>> d2['empty']
    Traceback (most recent call last):
        ...
    KeyError: 'empty'
    >>> d2.empty
    Traceback (most recent call last):
        ...
    AttributeError: 'Dict' object has no attribute 'empty'
    '''
    def __init__(self, **kw):
        super(Dict, self).__init__(**kw)

    def __getattr__(self, key):
        try:
            return self[key]
        except KeyError:
            raise AttributeError(r"'Dict' object has no attribute '%s'" % key)

    def __setattr__(self, key, value):
        self[key] = value

if __name__=='__main__':
    import doctest
    doctest.testmod()
```

`python mydict2.py`运行没有输出。因为编写的`doctest`运行正确。如果程序有问题，比如注释掉`__getattr__()`方法，就会报错:
```python
$ python mydict2.py
**********************************************************************
File "/Users/michael/Github/learn-python3/samples/debug/mydict2.py", line 10, in __main__.Dict
Failed example:
    d1.x
Exception raised:
    Traceback (most recent call last):
      ...
    AttributeError: 'Dict' object has no attribute 'x'
**********************************************************************
File "/Users/michael/Github/learn-python3/samples/debug/mydict2.py", line 16, in __main__.Dict
Failed example:
    d2.c
Exception raised:
    Traceback (most recent call last):
      ...
    AttributeError: 'Dict' object has no attribute 'c'
**********************************************************************
1 items had failures:
   2 of   9 in __main__.Dict
***Test Failed*** 2 failures.
```
注意之后3行代码。**当模块正常导入时，doctest不会被执行。只有在命令行直接运行时，才执行doctest**

